### ISSUE TITLE
Already patched ?

### ISSUE THREAD

**Issue by Mecanik** [thesecretclub/CVEAC-2020#1]
I may be wrong but, it seems they already patched this ? How fast.. I guess they got no life.

**Comment by hypervisor** [comment]
Got no life? It's literally their job to patch it...

**Comment by Mecanik** [comment]
> Got no life? It's literally their job to patch it...

DOH! Their "job" was supposed to be preventing something like this in the first place... but wait, all these "companies" created "next-gen" BS and sell for a shit ton of money when they cannot protect their own product...

If guys like you wouldn't hand them on a plate what to do, they would be worthless.

I better keep my thoughts to myself.

**Comment by hypervisor** [comment]
I'm not sure why you are blaming them for making mistakes like these, there are ALWAYS ways to circumvent their detections somehow, they can't possibly prevent everything. Yes they make some ridiculous mistakes sometimes but they are only human.

**Comment by vmcall** [comment]
why do you have to be this way
